language: c
compiler: gcc
sudo: false
dist: trusty

env:
  - TARGET=x86_64-linux-musl
  - TARGET=i486-linux-musl
  - TARGET=aarch64-linux-musl
  - TARGET=arm-linux-musleabi
  - TARGET=arm-linux-musleabihf


script:
  - bash build ${TARGET}

after_success:
  - bash upload
